steps:
  # 1. Build da imagem Docker
    - name: 'gcr.io/cloud-builders/docker'
    args:
            - 'build'
            - '-t'
            - '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:$BUILD_ID'
            - '.'

  # 2. Push da imagem pro Artifact Registry
    - name: 'gcr.io/cloud-builders/docker'
    args:
            - 'push'
            - '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:$BUILD_ID'

  # 3. Deploy no Cloud Run
    - name: 'gcr.io/google.com/cloudsdktool/ncloud-sdk'
    entrypoint: gcloud
    args:
            - 'run'
            - 'deploy'
            - '${_SERVICE_NAME}'
            - '--image'
            - '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:$BUILD_ID'
            - '--region'
            - '${_DEPLOY_REGION}'
            - '--platform'
            - '${_PLATFORM}'
            - '--allow-unauthenticated'

images:
    - '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:$BUILD_ID'
